import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import PageBreadcrumbButton from '@/components/Common/PageBreadcrumbButton';
import { Row, Col, Card, ListGroup } from 'react-bootstrap';
import { TableDragDrop, TableEditable, TableExpanding, TableFiltering, TablePagination, TableRowSelection, TableSorting, } from '@/components/UiElements/Tables/ReactTable';
const ReactTable = () => {
    return (_jsxs(_Fragment, { children: [_jsx(PageBreadcrumbButton, { title: "ReactTable", subName: "Tables", url: 'https://github.com/TanStack/table' }), _jsxs(Row, { className: "g-3 g-md-4", children: [_jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Sorting" }) }), _jsx(Card.Body, { className: "p-0", children: _jsx(TableSorting, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Filtering" }) }), _jsx(Card.Body, { className: "p-0", children: _jsx(TableFiltering, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Pagination" }) }), _jsx(Card.Body, { className: "p-0", children: _jsx(TablePagination, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Row Selection" }) }), _jsx(Card.Body, { className: "p-0", children: _jsx(TableRowSelection, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Expanding" }) }), _jsx(Card.Body, { className: "p-0", children: _jsx(TableExpanding, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Editable" }) }), _jsx(Card.Body, { className: "p-0", children: _jsx(TableEditable, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Drag & Drop" }) }), _jsx(Card.Body, { className: "p-0", children: _jsx(TableDragDrop, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsx(Card, { className: "border-0", children: _jsxs(ListGroup, { children: [_jsx(ListGroup.Item, { children: _jsx("h5", { className: "mb-0", children: "Uses Instruction" }) }), _jsxs(ListGroup.Item, { children: ["ReactTable is delivered primarily via npm.", ' ', _jsx("code", { children: "npm install @tanstack/react-table" })] }), _jsxs(ListGroup.Item, { children: ["For full documentation please visit the link:", _jsx(Link, { to: "https://github.com/TanStack/table", target: "_blank", children: "https://github.com/TanStack/table" })] })] }) }) })] })] }));
};
export default ReactTable;
