import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Col, Dropdown, Image, Row } from 'react-bootstrap';
import { Link } from 'react-router-dom';
import fullAvatar from '@/assets/images/general/full-avatar.png';
import BgCircleShapeStyle from '@/components/Misc/BgCircleShape';
import megaAppsItems from './data/magaMenuApps/megaAppsItems';
const MegaMenuApps = ({ isOpen, setIsOpen }) => {
    const megaMenuItemsClose = () => {
        setIsOpen(false);
    };
    return (_jsx(_Fragment, { children: _jsxs(Dropdown, { show: isOpen, onMouseEnter: () => setIsOpen(true), onMouseLeave: () => setIsOpen(false), className: "megumenu-dropdown megamenu-xl", children: [_jsx(Dropdown.Toggle, { variant: "", className: `btn-megumenu arrow-none ${isOpen ? 'show' : ''}`, id: "mega-menu-apps", "aria-expanded": isOpen ? 'true' : 'false', children: "Apps" }), _jsxs(Dropdown.Menu, { className: "megumenu-wrapper", children: [_jsxs("div", { className: "d-flex align-items-center gap-4 mx-n4 mt-n4 px-4 py-3 mb-4 border-bottom d-lg-none", style: { height: '3.5rem' }, onClick: megaMenuItemsClose, children: [_jsx("i", { className: "fi fi-rr-arrow-left" }), _jsx("span", { className: "text-dark", children: "Back" })] }), _jsxs("div", { className: "d-flex", children: [_jsxs("div", { className: "mb-4", children: [_jsx("h5", { className: "fw-semibold", children: "Applications" }), _jsx("span", { className: "fs-13 text-muted", children: "Available web appplications." })] }), _jsx("div", { className: "ms-auto", children: _jsxs(Link, { to: "", className: "ms-auto icon-link icon-link-hover link-primary", children: [_jsx("span", { children: "Explore Apps" }), _jsx("i", { className: "fi fi-rr-arrow-small-right bi" })] }) })] }), _jsxs(Row, { className: "g-12", children: [_jsx(Col, { lg: 8, children: _jsx(Row, { className: "g-4", children: megaAppsItems.map(({ to, title, desc, icon }, idx) => (_jsx(Col, { lg: 6, children: _jsx(Link, { to: to, className: "megumenu-item", children: _jsxs("div", { className: "d-flex gap-4", children: [_jsx("div", { className: "d-flex flex-shrink-0 align-items-center justify-content-center rounded bg-secondary-subtle text-dark", style: { width: '3rem', height: '3rem' }, children: _jsx("i", { className: `fi ${icon} fs-4 text-primary` }) }), _jsxs("div", { className: "d-flex flex-column", children: [_jsx("h6", { dangerouslySetInnerHTML: { __html: title } }), _jsx("span", { className: "fs-13 fw-normal text-muted text-truncate-2-line", children: desc })] })] }) }) }, idx))) }) }), _jsx(Col, { lg: 4, children: _jsx("div", { className: "p-4 d-flex align-items-center justify-content-center bg-secondary-subtle rounded-3", style: BgCircleShapeStyle, children: _jsx(Image, { src: fullAvatar, fluid: true, style: { maxHeight: '260px' } }) }) })] })] })] }) }));
};
export default MegaMenuApps;
