import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Col, Dropdown, Row, Image, Stack } from 'react-bootstrap';
import logoCircle from '@/assets/images/general/logo-circle.png';
import megaHomeItems from './data/megaMenuHome/megaHomeItems';
const MegaMenuHome = ({ isOpen, setIsOpen }) => {
    const megaMenuItemsClose = () => {
        setIsOpen(false);
    };
    return (_jsx(_Fragment, { children: _jsxs(Dropdown, { show: isOpen, onMouseEnter: () => setIsOpen(true), onMouseLeave: () => setIsOpen(false), className: "megumenu-dropdown megamenu-xxl", children: [_jsx(Dropdown.Toggle, { variant: "", className: `btn-megumenu arrow-none ${isOpen ? 'show' : ''}`, id: "mega-menu-home", "aria-expanded": isOpen ? 'true' : 'false', children: "Home" }), _jsxs(Dropdown.Menu, { className: "px-2 py-4 megumenu-wrapper", children: [_jsxs("div", { className: "d-flex align-items-center gap-4 mx-n4 mt-n4 px-4 py-3 mb-4 border-bottom d-lg-none", style: { height: '3.5rem' }, onClick: megaMenuItemsClose, children: [_jsx("i", { className: "fi fi-rr-arrow-left" }), _jsx("span", { className: "text-dark", children: "Back" })] }), _jsxs(Row, { className: "g-12", children: [_jsx(Col, { lg: 12, xl: 8, children: _jsx(Row, { className: "g-6", children: megaHomeItems.map(({ to, color, icon, title, description }, idx) => (_jsx(Col, { lg: 6, children: _jsx(Link, { to: to, className: "megumenu-item", children: _jsxs("div", { className: "d-flex gap-4", children: [_jsx("div", { className: `d-flex flex-shrink-0 align-items-center justify-content-center rounded  bg-${color}-subtle text-${color}`, style: { width: '3.5rem', height: '3.5rem' }, children: _jsx("i", { className: `fi ${icon} fs-3` }) }), _jsxs("div", { className: "d-flex flex-column", children: [_jsx("h6", { dangerouslySetInnerHTML: { __html: title } }), _jsx("span", { className: "fs-13 fw-normal text-muted text-truncate-2-line", children: description })] })] }) }) }, idx))) }) }), _jsx(Col, { xl: 4, className: "d-none d-xl-flex", children: _jsxs(Stack, { gap: 2, children: [_jsx("div", { className: "d-flex align-items-center justify-content-center border bg-secondary-subtle p-4 rounded-bottom-0 rounded-3", style: { minWidth: '250px' }, children: _jsx(Image, { src: logoCircle, fluid: true, style: { height: '250px' } }) }), _jsxs("div", { className: "px-4 py-3 border border-top-0 rounded-top rounded-3", style: { borderStyle: 'dashed' }, children: ["Freequently asks questios?", ' ', _jsx(Link, { to: "/other-pages/contact-us", className: "text-primary", children: "Contact" })] })] }) })] })] })] }) }));
};
export default MegaMenuHome;
