import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Carousel, Col, Dropdown, Image, Row } from 'react-bootstrap';
import carouselData from './data/megaManuPage/carouselData';
import { userProfileItems, accountSettingsItems, otherPagesItems, } from './data/megaManuPage/userProfileItems';
const MegaMenuPages = ({ isOpen, setIsOpen }) => {
    const megaMenuItemsClose = () => {
        setIsOpen(false);
    };
    return (_jsx(_Fragment, { children: _jsxs(Dropdown, { show: isOpen, onMouseEnter: () => setIsOpen(true), onMouseLeave: () => setIsOpen(false), className: "megumenu-dropdown megamenu-xxl", children: [_jsx(Dropdown.Toggle, { variant: "", className: `btn-megumenu arrow-none ${isOpen ? 'show' : ''}`, id: "mega-menu-pages", "aria-expanded": isOpen ? 'true' : 'false', children: "Pages" }), _jsxs(Dropdown.Menu, { className: "megumenu-wrapper", children: [_jsxs("div", { className: "d-flex align-items-center gap-4 mx-n4 mt-n4 px-4 py-3 mb-4 border-bottom d-lg-none", style: { height: '3.5rem' }, onClick: megaMenuItemsClose, children: [_jsx("i", { className: "fi fi-rr-arrow-left" }), _jsx("span", { className: "text-dark", children: "Back" })] }), _jsxs(Row, { className: "g-4", children: [_jsx(Col, { lg: 12, xl: 8, children: _jsxs(Row, { className: "g-4", children: [_jsxs(Col, { lg: 4, children: [_jsx("h5", { className: "fw-semibold mb-3", children: "Profile" }), userProfileItems.map(({ title, to }, idx) => (_jsx(Link, { to: to, className: "megumenu-item", children: _jsxs("span", { className: "d-flex align-items-center gap-3", children: [_jsx("span", { className: "d-flex bg-secondary bg-opacity-50 rounded-circle", style: { width: '0.25rem', height: '0.25rem' } }), _jsx("span", { children: title })] }) }, idx)))] }), _jsxs(Col, { lg: 4, children: [_jsx("h5", { className: "fw-semibold mb-3", children: "Settings" }), accountSettingsItems.map(({ title, to }, idx) => (_jsx(Link, { to: to, className: "megumenu-item", children: _jsxs("span", { className: "d-flex align-items-center gap-3", children: [_jsx("span", { className: "d-flex bg-secondary bg-opacity-50 rounded-circle", style: { width: '0.25rem', height: '0.25rem' } }), _jsx("span", { children: title })] }) }, idx)))] }), _jsxs(Col, { lg: 4, children: [_jsx("h5", { className: "fw-semibold mb-3", children: "Others" }), otherPagesItems.map(({ title, to }, idx) => (_jsx(Link, { to: to, className: "megumenu-item", children: _jsxs("span", { className: "d-flex align-items-center gap-3", children: [_jsx("span", { className: "d-flex bg-secondary bg-opacity-50 rounded-circle", style: { width: '0.25rem', height: '0.25rem' } }), _jsx("span", { children: title })] }) }, idx)))] })] }) }), _jsx(Col, { xl: 4, className: "d-none d-xl-flex", children: _jsx(Carousel, { indicators: false, children: carouselData.map(({ image }, index) => (_jsx(Carousel.Item, { className: "rounded-3 mt-3", children: _jsx("div", { className: "w-100 h-100 mx-auto text-center", children: _jsx(Image, { src: image, rounded: true, fluid: true, className: "rounded-3" }) }) }, index))) }) })] })] })] }) }));
};
export default MegaMenuPages;
