import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import BgCircleShapeStyle from '@/components/Misc/BgCircleShape';
import { Button, Col, Dropdown, Row } from 'react-bootstrap';
import 'react-circular-progressbar/dist/styles.css';
import { Link } from 'react-router-dom';
import { authItemsClassic, authItemsCorporate, authItemsCreative, authItemsModern, } from './data/magaMenuAuths/authPageItems';
const MegaMenuAuth = ({ isOpen, setIsOpen }) => {
    const megaMenuItemsClose = () => {
        setIsOpen(false);
    };
    return (_jsx(_Fragment, { children: _jsxs(Dropdown, { show: isOpen, onMouseEnter: () => setIsOpen(true), onMouseLeave: () => setIsOpen(false), className: "megumenu-dropdown megamenu-full", children: [_jsx(Dropdown.Toggle, { variant: "", className: `btn-megumenu arrow-none ${isOpen ? 'show' : ''}`, id: "mega-menu-auths", "aria-expanded": isOpen ? 'true' : 'false', children: "Auths" }), _jsxs(Dropdown.Menu, { className: "megumenu-wrapper", children: [_jsxs("div", { className: "d-flex align-items-center gap-4 mx-n4 mt-n4 px-4 py-3 mb-4 border-bottom d-lg-none", style: { height: '3.5rem' }, onClick: megaMenuItemsClose, children: [_jsx("i", { className: "fi fi-rr-arrow-left" }), _jsx("span", { className: "text-dark", children: "Back" })] }), _jsxs(Row, { className: "g-0", children: [_jsx(Col, { lg: 12, xxl: 9, children: _jsxs(Row, { className: "g-4", children: [_jsxs(Col, { lg: 3, children: [_jsx("h5", { className: "fw-semibold mb-3", children: "Classic" }), authItemsClassic.map(({ title, to }, idx) => (_jsx(Link, { to: to, className: "megumenu-item", children: _jsx("span", { children: title }) }, idx)))] }), _jsxs(Col, { lg: 3, children: [_jsx("h5", { className: "fw-semibold mb-3", children: "Creative" }), authItemsCreative.map(({ title, to }, idx) => (_jsx(Link, { to: to, className: "megumenu-item", children: _jsx("span", { children: title }) }, idx)))] }), _jsxs(Col, { lg: 3, children: [_jsx("h5", { className: "fw-semibold mb-3", children: "Corporate" }), authItemsCorporate.map(({ title, to }, idx) => (_jsx(Link, { to: to, className: "megumenu-item", children: _jsx("span", { children: title }) }, idx)))] }), _jsxs(Col, { lg: 3, children: [_jsx("h5", { className: "fw-semibold mb-3", children: "Modern" }), authItemsModern.map(({ title, to }, idx) => (_jsx(Link, { to: to, className: "megumenu-item", children: title }, idx)))] })] }) }), _jsx(Col, { xxl: 3, className: "px-4 py-8 py-lg-12 d-none d-xxl-flex flex-column align-items-center justify-content-center bg-secondary-subtle rounded-3 text-center border border-secondary border-opacity-10", style: BgCircleShapeStyle, children: _jsxs("div", { className: "mx-auto d-flex flex-column align-items-center justify-content-center", style: { maxWidth: '320px' }, children: [_jsx("div", { className: "text-primary mb-12", children: _jsx("i", { className: "fi fi-rs-rocket-lunch", style: { fontSize: '3rem', transform: 'rotate(320deg)', display: 'flex' } }) }), _jsx("h5", { className: "fw-bold mb-4 text-truncate", children: "Grow faster with pro's help" }), _jsx("p", { className: "fs-13 mb-8 text-muted text-truncate-3-line", children: "Experience top-notch features with our services and insights. Lorem ipsum dolor sit, amet consectetur adipisicing elit." }), _jsx(Button, { variant: "primary", children: "Get Started" })] }) })] })] })] }) }));
};
export default MegaMenuAuth;
