import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import MoviesData from './data/interested/MoviesData';
import MusicsData from './data/interested/MusicsData';
import BooksData from './data/interested/BooksData';
import GamesData from './data/interested/GamesData';
import HobbiesData from './data/interested/HobbiesData';
import EpisodesData from './data/interested/EpisodesData';
const OverviewInterested = () => {
    return (_jsxs(_Fragment, { children: [_jsx("h5", { className: "fw-semibold mb-5", children: "Interested" }), _jsxs("div", { className: "d-flex flex-wrap gap-1", children: [_jsx("div", { className: "text-muted me-3", children: "Movies: " }), MoviesData.map(({ name }, idx) => (_jsx(Link, { to: "#!", className: "py-1 px-2 border border-dashed rounded-pill fs-12", children: name }, idx)))] }), _jsx("hr", { style: { borderStyle: 'dashed' } }), _jsxs("div", { className: "d-flex flex-wrap gap-1", children: [_jsx("div", { className: "text-muted me-3", children: "Musics: " }), MusicsData.map(({ name }, idx) => (_jsx(Link, { to: "#!", className: "py-1 px-2 border border-dashed rounded-pill fs-12", children: name }, idx)))] }), _jsx("hr", { style: { borderStyle: 'dashed' } }), _jsxs("div", { className: "d-flex flex-wrap gap-1", children: [_jsx("div", { className: "text-muted me-3", children: "Books: " }), BooksData.map(({ name }, idx) => (_jsx(Link, { to: "#!", className: "py-1 px-2 border border-dashed rounded-pill fs-12", children: name }, idx)))] }), _jsx("hr", { style: { borderStyle: 'dashed' } }), _jsxs("div", { className: "d-flex flex-wrap gap-1", children: [_jsx("div", { className: "text-muted me-3", children: "Games: " }), GamesData.map(({ name }, idx) => (_jsx(Link, { to: "#!", className: "py-1 px-2 border border-dashed rounded-pill fs-12", children: name }, idx)))] }), _jsx("hr", { style: { borderStyle: 'dashed' } }), _jsxs("div", { className: "d-flex flex-wrap gap-1", children: [_jsx("div", { className: "text-muted me-3", children: "Hobbies: " }), HobbiesData.map(({ name }, idx) => (_jsx(Link, { to: "#!", className: "py-1 px-2 border border-dashed rounded-pill fs-12", children: name }, idx)))] }), _jsx("hr", { style: { borderStyle: 'dashed' } }), _jsxs("div", { className: "d-flex flex-wrap gap-1", children: [_jsx("div", { className: "text-muted me-3", children: "Episodes : " }), EpisodesData.map(({ name }, idx) => (_jsx(Link, { to: "#!", className: "py-1 px-2 border border-dashed rounded-pill fs-12", children: name }, idx)))] })] }));
};
export default OverviewInterested;
