import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import PageBreadcrumbButton from '@/components/Common/PageBreadcrumbButton';
import { Row, Col, Card, ListGroup } from 'react-bootstrap';
import { DropzoneAccepting, DropzoneBasic, DropzoneMaxFiles, DropzonePreviews, } from '@/components/UiElements/Extended/Dropzone';
const Dropzone = () => {
    return (_jsxs(_Fragment, { children: [_jsx(PageBreadcrumbButton, { title: "Dropzone", subName: "Extended", url: 'https://react-dropzone.js.org/' }), _jsxs(Row, { className: "g-3 g-md-4", children: [_jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Basic" }) }), _jsx(Card.Body, { children: _jsx(DropzoneBasic, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Accepting" }) }), _jsx(Card.Body, { children: _jsx(DropzoneAccepting, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "MaxFiles" }) }), _jsx(Card.Body, { children: _jsx(DropzoneMaxFiles, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Previews" }) }), _jsx(Card.Body, { children: _jsx(DropzonePreviews, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsx(Card, { className: "border-0", children: _jsxs(ListGroup, { children: [_jsx(ListGroup.Item, { children: _jsx("h5", { className: "mb-0", children: "Uses Instruction" }) }), _jsxs(ListGroup.Item, { children: ["Dropzone is delivered primarily via npm.", ' ', _jsx("code", { children: "npm install --save react-dropzone" })] }), _jsxs(ListGroup.Item, { children: ["For full documentation please visit the link:", _jsx(Link, { to: "https://react-dropzone.js.org/", target: "_blank", children: "https://react-dropzone.js.org/" })] })] }) }) })] })] }));
};
export default Dropzone;
