import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import PageBreadcrumbButton from '@/components/Common/PageBreadcrumbButton';
import { Row, Col, Card, ListGroup } from 'react-bootstrap';
import { SelectAnimation, SelectGrouped, SelectMultiple, SelectSingle, SelectStyleSingle, SelectStyleMultiple, SelectCreatable, SelectFixedOptions, SelectCustomSingle, SelectCustomMultiple, } from '@/components/UiElements/Extended/Selects';
const ReactSelect = () => {
    return (_jsxs(_Fragment, { children: [_jsx(PageBreadcrumbButton, { title: "Select2", subName: "Extended", url: 'https://react-select.com/home' }), _jsxs(Row, { className: "g-3 g-md-4", children: [_jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Single" }) }), _jsx(Card.Body, { children: _jsx(SelectSingle, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Grouped" }) }), _jsx(Card.Body, { children: _jsx(SelectGrouped, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Multiple" }) }), _jsx(Card.Body, { children: _jsx(SelectMultiple, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Animation" }) }), _jsx(Card.Body, { children: _jsx(SelectAnimation, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Single Style" }) }), _jsx(Card.Body, { children: _jsx(SelectStyleSingle, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Multiple Style" }) }), _jsx(Card.Body, { children: _jsx(SelectStyleMultiple, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Creatable" }) }), _jsx(Card.Body, { children: _jsx(SelectCreatable, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Fixed Options" }) }), _jsx(Card.Body, { children: _jsx(SelectFixedOptions, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Custom Single" }) }), _jsx(Card.Body, { children: _jsx(SelectCustomSingle, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Custom Multiple" }) }), _jsx(Card.Body, { children: _jsx(SelectCustomMultiple, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsx(Card, { className: "border-0", children: _jsxs(ListGroup, { children: [_jsx(ListGroup.Item, { children: _jsx("h5", { className: "mb-0", children: "Uses Instruction" }) }), _jsxs(ListGroup.Item, { children: ["Quill is delivered primarily via npm. ", _jsx("code", { children: "npm i --save react-select" })] }), _jsxs(ListGroup.Item, { children: ["For full documentation please visit the link:", _jsx(Link, { to: "https://react-select.com/home#getting-started", target: "_blank", children: "https://react-select.com/home#getting-started" })] })] }) }) })] })] }));
};
export default ReactSelect;
