import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import PageBreadcrumbButton from '@/components/Common/PageBreadcrumbButton';
import { Row, Col, Card, ListGroup } from 'react-bootstrap';
import { ToastifyPosition, ToastifyCustom, ToastifyStates, } from '@/components/UiElements/Extended/Toastify';
const Toastify = () => {
    return (_jsxs(_Fragment, { children: [_jsx(PageBreadcrumbButton, { title: "Toastify", subName: "Extended", url: 'https://fkhadra.github.io/react-toastify/introduction/' }), _jsxs(Row, { className: "g-3 g-md-4", children: [_jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Position" }) }), _jsx(Card.Body, { children: _jsx(ToastifyPosition, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "States" }) }), _jsx(Card.Body, { children: _jsx(ToastifyStates, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Custom" }) }), _jsx(Card.Body, { children: _jsx(ToastifyCustom, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsx(Card, { className: "border-0", children: _jsxs(ListGroup, { children: [_jsx(ListGroup.Item, { children: _jsx("h5", { className: "mb-0", children: "Uses Instruction" }) }), _jsxs(ListGroup.Item, { children: ["Toastify is delivered primarily via npm. ", _jsx("code", {})] }), _jsxs(ListGroup.Item, { children: ["For full documentation please visit the link:", _jsx(Link, { to: "https://fkhadra.github.io/react-toastify/installation", target: "_blank", children: "https://fkhadra.github.io/react-toastify/installation" })] })] }) }) })] })] }));
};
export default Toastify;
