import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import PageBreadcrumb from '@/components/Common/PageBreadcrumb';
import { Row, Col, Card, Table } from 'react-bootstrap';
import { AccrodionDefault, AccrodionFlush, AccrodionIcon, AccrodionOpened, AccrodionRevIcon, AccrodionReversed, } from '@/components/UiElements/Base/Accrodions';
const Accordions = () => {
    return (_jsxs(_Fragment, { children: [_jsx(PageBreadcrumb, { title: "Accrodions", subName: "Base UI" }), _jsxs(Row, { className: "g-3 g-md-4", children: [_jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Default" }) }), _jsx(Card.Body, { children: _jsx(AccrodionDefault, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Flush" }) }), _jsx(Card.Body, { children: _jsx(AccrodionFlush, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Opened" }) }), _jsx(Card.Body, { children: _jsx(AccrodionOpened, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Reversed" }) }), _jsx(Card.Body, { children: _jsx(AccrodionReversed, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Icon" }) }), _jsx(Card.Body, { children: _jsx(AccrodionIcon, {}) })] }) }), _jsx(Col, { lg: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "RevIcon" }) }), _jsx(Card.Body, { children: _jsx(AccrodionRevIcon, {}) })] }) }), _jsx(Col, { sm: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Options" }) }), _jsxs(Table, { className: "mb-0", responsive: true, children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Reference" }), _jsx("th", { children: "Details" })] }) }), _jsxs("tbody", { children: [_jsxs("tr", { children: [_jsx("td", { children: _jsx("code", { children: "Accordion" }) }), _jsx("td", { children: "Initializing bootstrap 5.3 accordion" })] }), _jsxs("tr", { children: [_jsx("td", { children: _jsx("code", { children: "Icon" }) }), _jsxs("td", { children: ["Add calss for custom icon", _jsx("code", { children: ".accordion + .accordion-icon" })] })] }), _jsxs("tr", { children: [_jsx("td", { children: _jsx("code", { children: "Reversed" }) }), _jsxs("td", { children: ["Add calss for reversed icon", _jsx("code", { children: ".accordion + .accordion-reversed" })] })] }), _jsxs("tr", { children: [_jsx("td", { children: _jsx("code", { children: "RevIcon" }) }), _jsxs("td", { children: ["Add calss for rev-icon icon", _jsx("code", { children: ".accordion + .accordion-rev-icon" })] })] }), _jsxs("tr", { children: [_jsx("td", { children: _jsx("code", { children: "Documentations" }) }), _jsxs("td", { children: ["Please visit:", _jsx(Link, { to: "https://react-bootstrap.netlify.app/docs/components/accordion", target: "_blank", rel: "noopener noreferrer", children: "https://react-bootstrap.netlify.app/docs/components/accordion" })] })] })] })] })] }) })] })] }));
};
export default Accordions;
