import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import PageBreadcrumbButton from '@/components/Common/PageBreadcrumbButton';
import { Row, Col, Card, ListGroup } from 'react-bootstrap';
import { DateRange, DateRangeMultiple, DateRangePicker, DateRangeWeekend, } from '@/components/UiElements/Pickers/DaterangePicker';
const DaterangePicker = () => {
    return (_jsxs(_Fragment, { children: [_jsx(PageBreadcrumbButton, { title: "DataRange", subName: "Pickers", url: 'https://hypeserver.github.io/react-date-range/' }), _jsxs(Row, { className: "g-3 g-md-4", children: [_jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "DateRange" }) }), _jsx(Card.Body, { children: _jsx(DateRange, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "DateRangeMultiple" }) }), _jsx(Card.Body, { children: _jsx(DateRangeMultiple, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "DateRangePicker" }) }), _jsx(Card.Body, { children: _jsx(DateRangePicker, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "DateRangeWeekend" }) }), _jsx(Card.Body, { children: _jsx(DateRangeWeekend, {}) })] }) }), _jsx(Col, { xs: 12, children: _jsx(Card, { className: "border-0", children: _jsxs(ListGroup, { children: [_jsx(ListGroup.Item, { children: _jsx("h5", { className: "mb-0", children: "Uses Instruction" }) }), _jsxs(ListGroup.Item, { children: ["Quill is delivered primarily via npm. ", _jsx("code", { children: "npm install react-date-range" })] }), _jsxs(ListGroup.Item, { children: ["For full documentation please visit the link:", _jsx(Link, { to: "https://hypeserver.github.io/react-date-range/", target: "_blank", children: "https://hypeserver.github.io/react-date-range/" })] })] }) }) })] })] }));
};
export default DaterangePicker;
