import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import PageBreadcrumbButton from '@/components/Common/PageBreadcrumbButton';
import { Row, Col, Card, ListGroup } from 'react-bootstrap';
import { FlatPickrBasic, FlatPickrDateTime, FlatPickrRange, FlatPickrHandler, FlatPickrMultiple, FlatPickrWeekNumber, } from '@/components/UiElements/Pickers/Flatpickr';
const Flatpickr = () => {
    return (_jsxs(_Fragment, { children: [_jsx(PageBreadcrumbButton, { title: "Flatpicker", subName: "Pickers", url: 'https://github.com/haoxins/react-flatpickr' }), _jsxs(Row, { className: "g-3 g-md-4", children: [_jsx(Col, { xs: 12, md: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Basic" }) }), _jsx(Card.Body, { children: _jsx(FlatPickrBasic, {}) })] }) }), _jsx(Col, { xs: 12, md: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "DateTime" }) }), _jsx(Card.Body, { children: _jsx(FlatPickrDateTime, {}) })] }) }), _jsx(Col, { xs: 12, md: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Multiple" }) }), _jsx(Card.Body, { children: _jsx(FlatPickrMultiple, {}) })] }) }), _jsx(Col, { xs: 12, md: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "weekNumbers" }) }), _jsx(Card.Body, { children: _jsx(FlatPickrWeekNumber, {}) })] }) }), _jsx(Col, { xs: 12, md: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "rangeCalendar" }) }), _jsx(Card.Body, { children: _jsx(FlatPickrRange, {}) })] }) }), _jsx(Col, { xs: 12, md: 6, children: _jsxs(Card, { children: [_jsx(Card.Header, { children: _jsx(Card.Title, { children: "Handler" }) }), _jsx(Card.Body, { children: _jsx(FlatPickrHandler, {}) })] }) }), _jsx(Col, { sm: 12, children: _jsx(Card, { className: "border-0", children: _jsxs(ListGroup, { children: [_jsx(ListGroup.Item, { children: _jsx("h5", { className: "mb-0", children: "Uses Instruction" }) }), _jsxs(ListGroup.Item, { children: ["Quill is delivered primarily via npm.", ' ', _jsx("code", { children: "npm install --save react-flatpickr" })] }), _jsxs(ListGroup.Item, { children: ["For full documentation please visit the link:", _jsx(Link, { to: "https://github.com/haoxins/react-flatpickr", target: "_blank", children: "https://github.com/haoxins/react-flatpickr" })] })] }) }) })] })] }));
};
export default Flatpickr;
